Ericsmrk/FS-CSCI150-F22-Team1-VR-Chess

start.html
This updoot should throw in a beautiful scene and drops in Jacob's work right into it.
=> Our First Conflict <3 

main_menu.html
Change to keep link menus linked
=> changed Join Game link to 'game_scene.html

README.md, index.html
added my email too, forgot that bit yesterday lol
=> did what Erik asked me to do

scripts/minecraft_demo.html, scripts/new_game_options.html
Added a testing file for game_scene called minecraft_demo. Changed new_game_options to load the new file. And updated game_scene_copy with the changes made to the new file. For example, implementing Mixins for the pieces. This will allow us to more easily implement Promotion in the future (pawn becomes a piece).
=> Implementing Piece Movement, part 1

gamescenes/js/interaction/piece_interaction.js
Credit goes to Jose for figuring this one out.
=> Implemented array to hold chess pieces and info

gamescenes/game_scene_copy.html, gamescenes/js/chess_piece_component, gamescenes/js/interaction/piece_interaction.js
https://millerjacob49.github.io/VR-Chess/ Checkout the GH pages to see the movement implementation in action. There are conflicts with this pull request, will need to use conflict editor to resolve.
=> Finished movement.

gamescenes/game_scene_copy.html, gamescenes/js/interaction/piece_interaction.js
Fixed bug with movement.
Corrected queen positioning.
Implemented security against change of environment breaking movement.
=> Fixed bug with movement.

game_scene.html, scripts/piece_interaction.js
=> Optimizing piece_interaction code and patching loader conflict

examples/js/chess_piece_component.js, examples/js/piece_interaction.js
Cleaned up piece interaction code a bit to make readability a bit better. 
Found bug with pawns that allowed illegal forward kills.
=> Pawn logic implemented for black pieces

examples/js/piece_interaction.js
Naive approach to logic, but works for now.
=> Implemented King logic for white side

examples/game_scene.html, examples/js/piece_interaction.js
trying to fix naf, this pull request is good now. 
The pieces however are not. Gg dudes
=> Revert "Trying to fix NAF"

examples/game_scene.html, examples/js/piece_interaction.js
currently working on getting the white knight to work
=> Scaling NAF stuff

examples/game_scene.html, examples/js/piece_interaction.js
=> Revert "Scaling NAF stuff"

examples/game_scene.html
TLDR: Broke both our repos, this should fix both our repos
don't ask questions
=> Fixed all the bsery

examples/game_scene.html
huge fix, fixes a lot of thigns
=> merge aasap please

examples/game_scene_dynamic.html, examples/game_scene_dynamic_light.html, examples/index.html, examples/js/dynamic-room.component.js
That's it pretty much. This will, in theory, now support as many people as needed
=> Added Dynamic rooms and multiple environments 

Documentation/mini_documentaion.txt
Adding Schemas to documentation
=> Adding Schemas to documentation

examples/game_scene.html, examples/js/piece_interaction.js
Minor bugfix for networked piece movement
=> Minor bugfix for networked piece movement

examples/game_scene.html, examples/index.html, examples/index_old.html, examples/js/piece_interaction.js, examples/js/setAtts.js, examples/src/scenes/scene2.json
Also changed some equations to be more intuitive.
=> Moved position of everything to center.

examples/index.html, examples/js/color_changer_component.js
Pseudorandom deterministic color changing components created. Preparing for data transfer between scenes down the line.
=> Color changing function work

examples/game_scene.html, examples/index.html, examples/js/color_changer_component.js, examples/js/piece_color_component.js
Implemented framework for color shifting and added room code submit form.
=> Completing color framework.

examples/index.html, examples/js/color_changer_component.js, examples/js/splash_screen_camera.js
New color options are also possible. Also prettied up menu further.
=> Color changing finished

examples/game_scene.html, examples/index.html, examples/js/Loader.js, examples/js/color_changer_component.js, examples/js/selector-component.js, examples/js/setAtts.js, examples/src/scenes/scene1.json
Scenes, color, and room code can be selected from the main menu.
=> Data transfer between menu and scene done.

examples/index.html, examples/logged_in.html
-removed line of code that causes pop-up window.
=> removed popup window
